[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "mdhtml2term"
dynamic = ["version"]
description = "Render MDHTML in the terminal with Rich"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [{name = "Jeremy Howard", email = "github@jhoward.fastmail.fm"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = []

[project.optional-dependencies]
dev = [
  "fastship",
  "build",
  "twine",
]

[project.urls]
Homepage = "https://github.com/AnswerDotAI/mdhtml2term"

[tool.setuptools.dynamic]
version = { attr = "mdhtml2term.__version__" }

[tool.setuptools.packages.find]
include = ["mdhtml2term"]
